### ISSUE TITLE
If logged in – top left corner (FullHouse) icon needs to link to dashboard page.

### ISSUE THREAD

**Issue by cmoiceanu** [Full-House-UW/fullhouse#88] opened 2012-11-04 07:43 UTC
If I am logged in, when I click the top left corner (FullHouse) icon I should be sent back to dashboard page rather than back to “Welcome” page to login again (since I am already logged in).

**Comment by natmote** [comment] 2012-11-04 07:44
This is essentially a duplicate of #85

**Closed as completed by natmote** 2012-11-04 07:44 UTC
Labels: bug, duplicate
