### ISSUE TITLE
Task due date accepts arbitrary values

### ISSUE THREAD

**Issue by natmote** [Full-House-UW/fullhouse#176] opened 2012-11-19 06:18 UTC
The due date does not need to be a date. I assume that this was not by design. I'm actually a little bit confused about how this even works, because I thought it was a date field.

**Comment by creisman** [comment] 2012-11-19 06:24
Yeah, it's kind of botched... We merged tasks and task instances for this
release and will break them apart in the future. The problem is for this
release it needs to be a date. For future releases it will be a time... It
just spits out whatever value you enter, which isn't ideal, but functions
somewhat. I suppose a raw string is not better than a date since we'd have
to change either one. To be "proper" we would need to change it to a date
for this release.

**Comment by creisman** [comment] 2012-11-19 06:36
I'm handing this off to Jeff since he handled the models.

**Comment by j3ffml** [comment] 2012-11-19 21:19
#180 fixed this

**Closed as completed by j3ffml** 2012-11-19 21:19 UTC
