### ISSUE TITLE
Create House page has weird behavior on validation error

### ISSUE THREAD

**Issue by natmote** [Full-House-UW/fullhouse#141] opened 2012-11-18 19:32 UTC
If you enter an invalid zipcode in the create house page, the error message appears, but the form collapses.

**Comment by j3ffml** [comment] 2012-11-18 19:37
I was just looking at that. The problem is that the create house form is triggered to appear using javascript, and does not appear by default. You can fix that by checking to see if the form has any data in it in window.onload(), and if so, display the form.

**Comment by snuriel92** [comment] 2012-11-18 20:05
I re-assigned to Conor for the moment since he did more of the Create a house functionality and I can't really view Full House at the moment (working on that with Jeff) so I'll take a look as soon as I can

**Comment by creisman** [comment] 2012-11-18 20:05
Aw crap. I knew I forgot something. I'll get this hooked up in a sec.

**Comment by natmote** [comment] 2012-11-18 21:02
you didn't forget it -- I added validation, so before, there weren't any errors to display.

**Comment by creisman** [comment] 2012-11-18 21:03
Yeah but I thought about that case and meant to add handling for it. And I think there was required/non-required before, wasn't there?

Fixed in #147.

**Closed as completed** 2012-11-18 21:10 UTC
Labels: bug
