### ISSUE TITLE
Registration page gives error for null birthday field

### ISSUE THREAD

**Issue by snuriel92** [Full-House-UW/fullhouse#139] opened 2012-11-18 18:59 UTC
So I create an account with my email and password and see this error
http://oi49.tinypic.com/sllc86.jpg
However, I still get the validation link 'sent' to me...

**Comment by j3ffml** [comment] 2012-11-18 19:02
That's a problem with the UserProfile model. I'll fix it

**Comment by j3ffml** [comment] 2012-11-18 19:05
Actually, I can't get the bug to reproduce on my machine. Are you sure your database is up to date? Run `./convert_to_south.sh` and try again.

**Comment by snuriel92** [comment] 2012-11-18 19:20
Ya, I did that..This is what showed up on my terminal when I did that:
(env)[snuriel@localhost fullhouse]$ ./convert_to_south.sh 
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 1 object(s) from 1 fixture(s)

Synced:

> fullhouse.auth
> django.contrib.auth
> registration
> emailusernames
> django.contrib.contenttypes
> django.contrib.sessions
> django.contrib.sites
> django.contrib.messages
> django.contrib.staticfiles
> south

Not synced (use migrations):
- fullhouse.dashboard
  (use ./manage.py migrate to migrate these)
- Soft matched migration 0001 to 0001_initial.
  Running migrations for dashboard:
- Migrating backwards to just after 0001_initial.
  < dashboard:0003_auto__del_field_announcement_title
   (faked)
  < dashboard:0002_auto__add_field_announcement_expiration
   (faked)
  Running migrations for dashboard:
- Migrating forwards to 0003_auto__del_field_announcement_title.
  > dashboard:0002_auto__add_field_announcement_expiration
  > dashboard:0003_auto__del_field_announcement_title
- Loading initial data for dashboard.
  Installed 1 object(s) from 1 fixture(s)

**Comment by natmote** [comment] 2012-11-18 19:23
What probably happened is you had a database in a state that is not described by any of the migrations. Maybe you made some changes that the migrations don't take into account, then went back and tried to use the migrations.

I'm not actually a south expert, so I don't know what happened.

You can just delete your database file and run syncdb and migrate, and then you should be set.

Hopefully this doesn't happen in our real release...

**Comment by snuriel92** [comment] 2012-11-18 20:15
So I did that (after emailing with @jlowdermilk  for a long time) and was told that everything was synced except fullhouse.dashboard which needed t ob e synced with ./manage.py migrate. I did that and it all looked good and then I ran Jeff's migration scripts and it said everything was successful! And then I ran ./manage.py runserver and got to our Welcome page, logged in and am still on the error page"
"DoesNotExist at /dashboard/
UserProfile matching query does not exist"

**Comment by j3ffml** [comment] 2012-11-18 20:39
I'm looking into a solution now. The problem is that our use of south has broken the migration script I wrote to deal with existing users.

**Comment by j3ffml** [comment] 2012-11-18 22:12
This should be covered by updated migration script in #148. Marking it as closed.

**Closed as completed by j3ffml** 2012-11-18 22:12 UTC
Labels: bug
